In [1]:
import pandas as pd

In [2]:
orig = pd.read_csv("/oak/stanford/groups/akundaje/projects/cad/data/clint_data/rasqual_results/revisions/smc/SMC_rasqual_results_FDR_0.05_083121.txt", sep="\t", header=0)

In [3]:
orig.head()

,Feature_ID,rsID,Chromosome,SNP_position,Ref_allele,Alt_allele,Freq,HWE_Chisquare,Imp_quality,Log10_BH_Q,...,Distance to TSS,Nearest PromoterID,Entrez ID,Nearest Unigene,Nearest Refseq,Nearest Ensembl,Gene Name,Gene Alias,Gene Description,Gene Type
0,chr1.1069225.1069626,rs74048003,chr1,1067007,A,G,0.2000,0.156250,0.999916,-4.920961,...,4881,NM_001205252,401934.0,Hs.568137,NM_001205252,ENSG00000237330,RNF223,-,ring finger protein 223,protein-coding
1,chr1.108118484.108118885,rs665659,chr1,108121219,C,G,0.7250,0.000393,0.999935,-4.118572,...,74124,NM_213651,29957.0,Hs.656870,NM_013386,ENSG00000085491,SLC25A24,APC1|SCAMC-1|SCAMC1,solute carrier family 25 member 24,protein-coding
2,chr1.108721337.108721738,rs4970806,chr1,108721447,C,T,0.6625,5.930399,0.999939,-9.266900,...,8604,NM_001144937,163479.0,Hs.258253,NM_173532,ENSG00000143107,FNDC7,-,fibronectin type III domain containing 7,protein-coding
3,chr1.108841698.108842099,rs34272714,chr1,108842308,G,C,0.1375,1.016593,0.999885,-4.721082,...,15205,NM_152763,254268.0,Hs.729441,NM_152763,ENSG00000162641,AKNAD1,C1orf62,AKNA domain containing 1,protein-coding
4,chr1.109274794.109275195,rs611917,chr1,109272630,A,G,0.2750,5.566376,0.999931,-3.006430,...,8149,NM_001350237,84722.0,Hs.405925,NM_032636,ENSG00000134222,PSRC1,DDA3|FP3214,proline and serine rich coiled-coil 1,protein-coding

In [4]:
orig.columns

Index(['Feature_ID', 'rsID', 'Chromosome', 'SNP_position', 'Ref_allele',
       'Alt_allele', 'Freq', 'HWE_Chisquare', 'Imp_quality', 'Log10_BH_Q',
       'Chisquare', 'Effect_size', 'Delta', 'Phi', 'Overdispersion',
       'SNP_id_region', 'Num_feature_SNPs', 'Num_tested_SNPs',
       'Num_iterations_null', 'Num_iterations_alt', 'Random_ties',
       'Log_likelihood_null', 'Convergence_status', 'Sq_corr_fSNPs',
       'Sq_corr_rSNP', 'P', 'q', 'keep', 'PeakID', 'Chr', 'Start', 'End',
       'Strand', 'Peak Score', 'Focus Ratio/Region Size', 'Annotation',
       'Detailed Annotation', 'Distance to TSS', 'Nearest PromoterID',
       'Entrez ID', 'Nearest Unigene', 'Nearest Refseq', 'Nearest Ensembl',
       'Gene Name', 'Gene Alias', 'Gene Description', 'Gene Type'],
      dtype='object')

In [5]:
preds = pd.read_csv("/mnt/lab_data2/anusri/variant-scorer/src/output/smc_caqtls/ATAC_sig_only_new/summary.mean.variant_scores_new.tsv", sep="\t", header=0)

In [6]:
preds.shape

(1984, 23)

In [7]:
import numpy as np
preds["jsd.sign.mean"] = np.sign(preds["logfc.mean"])* preds["jsd.mean"]

In [8]:
preds.head()

,chr,pos,allele1,allele2,rsid,logfc.mean,abs_logfc.mean,abs_logfc.mean.pval,jsd.mean,jsd.mean.pval,...,max_percentile.mean.pval,logfc_x_max_percentile.mean,abs_logfc_x_max_percentile.mean,abs_logfc_x_max_percentile.mean.pval,jsd_x_max_percentile.mean,jsd_x_max_percentile.mean.pval,abs_logfc_x_jsd_x_max_percentile.mean,abs_logfc_x_jsd_x_max_percentile.mean.pval,logfc_x_jsd_x_max_percentile.mean,jsd.sign.mean
0,chr1,1067007,A,G,"chr1.1069225.1069626,rs74048003,chr1,1067007,A...",0.022735,0.027306,0.525433,0.008771,0.578309,...,0.071857,0.015619,0.019011,0.247607,0.005870,0.175994,0.000209,0.302285,0.000184,0.008771
1,chr1,108121219,C,G,"chr1.108118484.108118885,rs665659,chr1,1081212...",0.021728,0.026806,0.533548,0.009595,0.513887,...,0.097398,0.013720,0.016709,0.288160,0.005725,0.178482,0.000164,0.334105,0.000141,0.009595
2,chr1,108721447,C,T,"chr1.108721337.108721738,rs4970806,chr1,108721...",0.289341,0.289341,0.034743,0.031146,0.047851,...,0.138296,0.148480,0.148480,0.018484,0.015681,0.031848,0.004771,0.023252,0.004771,0.031146
3,chr1,108842308,G,C,"chr1.108841698.108842099,rs34272714,chr1,10884...",-0.293381,0.293381,0.031649,0.041953,0.023738,...,0.193577,-0.127705,0.127705,0.023055,0.018106,0.024531,0.005598,0.019474,-0.005598,-0.041953
4,chr1,109272630,A,G,"chr1.109274794.109275195,rs611917,chr1,1092726...",0.100375,0.100375,0.171206,0.016716,0.188809,...,0.139277,0.051331,0.051331,0.086704,0.008469,0.103948,0.000975,0.102504,0.000975,0.016716

In [9]:
preds = preds[["chr", "pos", "allele1", "allele2", "logfc.mean", "jsd.sign.mean"]]

In [10]:
orig = orig.merge(preds, left_on=['Chromosome', 'SNP_position', 'Ref_allele','Alt_allele'], right_on=["chr", "pos", "allele1", "allele2"]).drop_duplicates()

In [11]:
orig.columns

Index(['Feature_ID', 'rsID', 'Chromosome', 'SNP_position', 'Ref_allele',
       'Alt_allele', 'Freq', 'HWE_Chisquare', 'Imp_quality', 'Log10_BH_Q',
       'Chisquare', 'Effect_size', 'Delta', 'Phi', 'Overdispersion',
       'SNP_id_region', 'Num_feature_SNPs', 'Num_tested_SNPs',
       'Num_iterations_null', 'Num_iterations_alt', 'Random_ties',
       'Log_likelihood_null', 'Convergence_status', 'Sq_corr_fSNPs',
       'Sq_corr_rSNP', 'P', 'q', 'keep', 'PeakID', 'Chr', 'Start', 'End',
       'Strand', 'Peak Score', 'Focus Ratio/Region Size', 'Annotation',
       'Detailed Annotation', 'Distance to TSS', 'Nearest PromoterID',
       'Entrez ID', 'Nearest Unigene', 'Nearest Refseq', 'Nearest Ensembl',
       'Gene Name', 'Gene Alias', 'Gene Description', 'Gene Type', 'chr',
       'pos', 'allele1', 'allele2', 'logfc.mean', 'jsd.sign.mean'],
      dtype='object')

In [12]:
orig = orig[['Chromosome', 'SNP_position', 'Ref_allele', 'Alt_allele', 'Log10_BH_Q', 'Effect_size', 'logfc.mean', 'jsd.sign.mean']]

In [13]:
peaks_bed = pd.read_csv("/oak/stanford/groups/akundaje/projects/cad/outs/7_30_2023_human_all_models/peaks/original/SMC.peaks.bed", sep="\t", header=None)

In [14]:
peaks_bed.head()

,0,1,2,3,4,5,6,7,8,9
0,chr1,2,624982,SMC_m2PE_peak_1,1978,.,8.30810,200.48422,197.87073,181479
1,chr1,639033,773662,SMC_m2PE_peak_2,140,.,2.44222,15.88614,14.09891,131441
2,chr1,778301,779293,SMC_m2PE_peak_3,13192,.,12.68989,1324.53931,1319.24121,428
3,chr1,783770,822546,SMC_m2PE_peak_4,4017,.,10.95845,404.78445,401.77557,33595
4,chr1,826698,827834,SMC_m2PE_peak_5,11889,.,14.98692,1193.70923,1188.91516,827

In [15]:
orig["pos0"] = orig["SNP_position"] - 1
selected_beds = orig[['Chromosome', "pos0", 'SNP_position', 'Ref_allele', 'Alt_allele', 'Log10_BH_Q', 'Effect_size', 'logfc.mean', 'jsd.sign.mean']]

selected_beds

,Chromosome,pos0,SNP_position,Ref_allele,Alt_allele,Log10_BH_Q,Effect_size,logfc.mean,jsd.sign.mean
0,chr1,1067006,1067007,A,G,-4.920961,0.200715,0.022735,0.008771
1,chr1,108121218,108121219,C,G,-4.118572,0.228169,0.021728,0.009595
2,chr1,108721446,108721447,C,T,-9.266900,0.764114,0.289341,0.031146
3,chr1,108842307,108842308,G,C,-4.721082,0.242912,-0.293381,-0.041953
4,chr1,109272629,109272630,A,G,-3.006430,0.709092,0.100375,0.016716
...,...,...,...,...,...,...,...,...,...
2033,chr9,96159156,96159157,C,T,-3.026381,0.806026,-0.104170,-0.024419
2034,chr9,96178224,96178225,G,A,-4.596132,0.787369,0.016330,0.007556
2035,chr9,97227899,97227900,A,T,-2.961709,0.405945,-0.000896,-0.007822
2036,chr9,98873906,98873907,T,C,-4.182089,0.608833,-0.040235,-0.008717
2037,chr9,99444663,99444664,G,A,-4.616533,0.279315,0.060264,0.012065

In [16]:
peaks_bed[1] = peaks_bed[1] + peaks_bed[9] - 100
peaks_bed[2] = peaks_bed[1] + 200

In [17]:
peaks_bed

,0,1,2,3,4,5,6,7,8,9
0,chr1,181381,181581,SMC_m2PE_peak_1,1978,.,8.30810,200.48422,197.87073,181479
1,chr1,770374,770574,SMC_m2PE_peak_2,140,.,2.44222,15.88614,14.09891,131441
2,chr1,778629,778829,SMC_m2PE_peak_3,13192,.,12.68989,1324.53931,1319.24121,428
3,chr1,817265,817465,SMC_m2PE_peak_4,4017,.,10.95845,404.78445,401.77557,33595
4,chr1,827425,827625,SMC_m2PE_peak_5,11889,.,14.98692,1193.70923,1188.91516,827
...,...,...,...,...,...,...,...,...,...,...
122115,chrY,56831818,56832018,SMC_m2PE_peak_122116,66,.,1.44943,7.93707,6.62112,223
122116,chrY,56836744,56836944,SMC_m2PE_peak_122117,163,.,1.74992,18.21555,16.36313,135
122117,chrY,56850861,56851061,SMC_m2PE_peak_122118,236,.,2.47251,25.62169,23.66050,373
122118,chrY,56870843,56871043,SMC_m2PE_peak_122119,292,.,3.14725,31.30095,29.28865,73
122119,chrY,56873684,56873884,SMC_m2PE_peak_122120,39,.,1.68549,5.09318,3.92608,36

In [18]:
import pybedtools
beds_var = pybedtools.BedTool.from_dataframe(selected_beds)
peak_bed =  pybedtools.BedTool.from_dataframe(peaks_bed)
sig_vars_in_bed = beds_var.intersect(peak_bed, c=True)

In [19]:
sig_vars_in_bed = sig_vars_in_bed.to_dataframe(names=['Chromosome', "pos0", 'SNP_position', 'Ref_allele', 'Alt_allele', 'Log10_BH_Q', 'Effect_size', 'logfc.mean', 'jsd.sign.mean', "hits"]).drop_duplicates()

In [20]:
sig_vars_in_bed.head()

,Chromosome,pos0,SNP_position,Ref_allele,Alt_allele,Log10_BH_Q,Effect_size,logfc.mean,jsd.sign.mean,hits
0,chr1,1067006,1067007,A,G,-4.920961,0.200715,0.022735,0.008771,0
1,chr1,108121218,108121219,C,G,-4.118572,0.228169,0.021728,0.009595,0
2,chr1,108721446,108721447,C,T,-9.266900,0.764114,0.289341,0.031146,1
3,chr1,108842307,108842308,G,C,-4.721082,0.242912,-0.293381,-0.041953,0
4,chr1,109272629,109272630,A,G,-3.006430,0.709092,0.100375,0.016716,0

In [21]:
sig_vars_in_bed.shape

(1984, 10)

In [22]:
sig_vars_in_bed

,Chromosome,pos0,SNP_position,Ref_allele,Alt_allele,Log10_BH_Q,Effect_size,logfc.mean,jsd.sign.mean,hits
0,chr1,1067006,1067007,A,G,-4.920961,0.200715,0.022735,0.008771,0
1,chr1,108121218,108121219,C,G,-4.118572,0.228169,0.021728,0.009595,0
2,chr1,108721446,108721447,C,T,-9.266900,0.764114,0.289341,0.031146,1
3,chr1,108842307,108842308,G,C,-4.721082,0.242912,-0.293381,-0.041953,0
4,chr1,109272629,109272630,A,G,-3.006430,0.709092,0.100375,0.016716,0
...,...,...,...,...,...,...,...,...,...,...
1979,chr9,96159156,96159157,C,T,-3.026381,0.806026,-0.104170,-0.024419,0
1980,chr9,96178224,96178225,G,A,-4.596132,0.787369,0.016330,0.007556,0
1981,chr9,97227899,97227900,A,T,-2.961709,0.405945,-0.000896,-0.007822,0
1982,chr9,98873906,98873907,T,C,-4.182089,0.608833,-0.040235,-0.008717,0
1983,chr9,99444663,99444664,G,A,-4.616533,0.279315,0.060264,0.012065,0

In [23]:
sig_vars_in_bed["IsUsed"] = sig_vars_in_bed["hits"] > 0

In [24]:
sig_vars_in_bed

,Chromosome,pos0,SNP_position,Ref_allele,Alt_allele,Log10_BH_Q,Effect_size,logfc.mean,jsd.sign.mean,hits,IsUsed
0,chr1,1067006,1067007,A,G,-4.920961,0.200715,0.022735,0.008771,0,False
1,chr1,108121218,108121219,C,G,-4.118572,0.228169,0.021728,0.009595,0,False
2,chr1,108721446,108721447,C,T,-9.266900,0.764114,0.289341,0.031146,1,True
3,chr1,108842307,108842308,G,C,-4.721082,0.242912,-0.293381,-0.041953,0,False
4,chr1,109272629,109272630,A,G,-3.006430,0.709092,0.100375,0.016716,0,False
...,...,...,...,...,...,...,...,...,...,...,...
1979,chr9,96159156,96159157,C,T,-3.026381,0.806026,-0.104170,-0.024419,0,False
1980,chr9,96178224,96178225,G,A,-4.596132,0.787369,0.016330,0.007556,0,False
1981,chr9,97227899,97227900,A,T,-2.961709,0.405945,-0.000896,-0.007822,0,False
1982,chr9,98873906,98873907,T,C,-4.182089,0.608833,-0.040235,-0.008717,0,False
1983,chr9,99444663,99444664,G,A,-4.616533,0.279315,0.060264,0.012065,0,False

In [25]:
cols=['Chromosome', 'SNP_position', 'Ref_allele', 'Alt_allele', 'Log10_BH_Q', 'Effect_size', 'logfc.mean', 'jsd.sign.mean', "IsUsed"]

sig_vars_in_bed[cols].to_csv("/mnt/lab_data2/anusri/chrombpnet/src/evaluation/figure_notebooks/figure_6/final_figures_new/smc.caqtls.tsv", sep="\t", header=True, index=False)