In [1]:
import pandas as pd
dttype = 'ATAC'
counts = []
mode = "counts"

rows = []
for celltype in ["GM12878", "HEPG2", "K562", "IMR90", "H1ESC"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    tomtom = tomtom[tomtom["num_seqlets"]>=100]
    rows.append([celltype, "ATAC" , sum(tomtom["pattern"].str.contains("pos_patterns")),
                 sum(tomtom["pattern"].str.contains("neg_patterns")), sum(tomtom["pattern"].str.contains("_patterns"))])
    #rows.append([celltype, "ATAC" , "COUNTS-", sum(tomtom["pattern"].str.contains("neg_patterns"))])

    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    
mode = "profile"
i = 0
for celltype in ["GM12878", "HEPG2", "K562", "IMR90", "H1ESC"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    tomtom = tomtom[tomtom["num_seqlets"]>=100]
    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("neg_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("_patterns")))
    #rows.append([celltype, "ATAC" , "PROFILE+", sum(tomtom["pattern"].str.contains("pos_patterns"))])
    #rows.append([celltype, "ATAC" , "PROFILE-", sum(tomtom["pattern"].str.contains("neg_patterns"))])
    i+=1
    #counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
   
dttype = 'DNASE'
mode = "counts"
for celltype in ["GM12878_new", "HEPG2", "K562", "IMR90_new", "H1ESC_new"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    tomtom = tomtom[tomtom["num_seqlets"]>=100]
    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
#     rows.append([celltype.replace("_new", ""), "DNASE" , "COUNTS+", sum(tomtom["pattern"].str.contains("pos_patterns"))])    
#     rows.append([celltype.replace("_new", ""), "DNASE" , "COUNTS-", sum(tomtom["pattern"].str.contains("neg_patterns"))])
    rows.append([celltype, "DNASE" , sum(tomtom["pattern"].str.contains("pos_patterns")),
                 sum(tomtom["pattern"].str.contains("neg_patterns")), sum(tomtom["pattern"].str.contains("_patterns"))])

    
mode = "profile"
i = 5
for celltype in ["GM12878_new", "HEPG2", "K562", "IMR90_new", "H1ESC_new"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    tomtom = tomtom[tomtom["num_seqlets"]>=100]
    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
#     rows.append([celltype.replace("_new", ""), "DNASE" , "PROFILE+", sum(tomtom["pattern"].str.contains("pos_patterns"))])
#     rows.append([celltype.replace("_new", ""), "DNASE" , "PROFILE-", sum(tomtom["pattern"].str.contains("neg_patterns"))])
    rows[i].append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("neg_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("_patterns")))

    i+=1

In [2]:
import pandas as pd

In [3]:
data = pd.DataFrame(rows)

In [4]:
data.to_csv("modisco_distribution_filt.tsv", sep="\t", header=False, index=False)

In [5]:
data

             0      1   2  3   4   5   6    7
0      GM12878   ATAC  41  1  42  48  66  114
1        HEPG2   ATAC  43  0  43  61  18   79
2         K562   ATAC  33  8  41  53   4   57
3        IMR90   ATAC  45  2  47  63  32   95
4        H1ESC   ATAC  34  0  34  39  18   57
5  GM12878_new  DNASE  30  0  30  45  36   81
6        HEPG2  DNASE  45  0  45  55  41   96
7         K562  DNASE  26  0  26  47  13   60
8    IMR90_new  DNASE  42  1  43  45  27   72
9    H1ESC_new  DNASE  26  0  26  35  14   49