In [15]:
import pandas as pd
dttype = 'ATAC'
counts = []
mode = "counts"

rows = []
for celltype in ["GM12878", "HEPG2", "K562", "IMR90", "H1ESC"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    rows.append([celltype, "ATAC" , sum(tomtom["pattern"].str.contains("pos_patterns")),
                 sum(tomtom["pattern"].str.contains("neg_patterns")), sum(tomtom["pattern"].str.contains("_patterns"))])
    #rows.append([celltype, "ATAC" , "COUNTS-", sum(tomtom["pattern"].str.contains("neg_patterns"))])

    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    
mode = "profile"
i = 0
for celltype in ["GM12878", "HEPG2", "K562", "IMR90", "H1ESC"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("neg_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("_patterns")))
    #rows.append([celltype, "ATAC" , "PROFILE+", sum(tomtom["pattern"].str.contains("pos_patterns"))])
    #rows.append([celltype, "ATAC" , "PROFILE-", sum(tomtom["pattern"].str.contains("neg_patterns"))])
    i+=1
    #counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
   
dttype = 'DNASE'
mode = "counts"
for celltype in ["GM12878_new", "HEPG2", "K562", "IMR90_new", "H1ESC_new"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
#     rows.append([celltype.replace("_new", ""), "DNASE" , "COUNTS+", sum(tomtom["pattern"].str.contains("pos_patterns"))])    
#     rows.append([celltype.replace("_new", ""), "DNASE" , "COUNTS-", sum(tomtom["pattern"].str.contains("neg_patterns"))])
    rows.append([celltype, "DNASE" , sum(tomtom["pattern"].str.contains("pos_patterns")),
                 sum(tomtom["pattern"].str.contains("neg_patterns")), sum(tomtom["pattern"].str.contains("_patterns"))])

    
mode = "profile"
i = 5
for celltype in ["GM12878_new", "HEPG2", "K562", "IMR90_new", "H1ESC_new"]:
    htmld="/oak/stanford/groups/akundaje/projects/chromatin-atlas-2022/chrombpnet/folds/"+dttype+'/'+celltype+"/merge_folds_new_may_05_24/"+mode+"/motifs.html"
    tomtom = pd.read_html(htmld)[0]
    counts.append(sum(tomtom["pattern"].str.contains("pos_patterns")))
#     rows.append([celltype.replace("_new", ""), "DNASE" , "PROFILE+", sum(tomtom["pattern"].str.contains("pos_patterns"))])
#     rows.append([celltype.replace("_new", ""), "DNASE" , "PROFILE-", sum(tomtom["pattern"].str.contains("neg_patterns"))])
    rows[i].append(sum(tomtom["pattern"].str.contains("pos_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("neg_patterns")))
    rows[i].append(sum(tomtom["pattern"].str.contains("_patterns")))

    i+=1

In [16]:
import pandas as pd

In [17]:
data = pd.DataFrame(rows)

In [18]:
data.to_csv("modisco_distribution.tsv", sep="\t", header=False, index=False)

In [19]:
data

             0      1   2   3   4   5   6    7
0      GM12878   ATAC  56   2  58  63  90  153
1        HEPG2   ATAC  54   7  61  81  29  110
2         K562   ATAC  43  18  61  62   9   71
3        IMR90   ATAC  58   4  62  87  39  126
4        H1ESC   ATAC  45   4  49  53  27   80
5  GM12878_new  DNASE  47   2  49  58  53  111
6        HEPG2  DNASE  59   5  64  80  57  137
7         K562  DNASE  39   0  39  66  14   80
8    IMR90_new  DNASE  70   1  71  79  38  117
9    H1ESC_new  DNASE  35   0  35  50  22   72